FROM node:21-alpine3.17

WORKDIR /usr/src/app

COPY nginx/ .

RUN npm install

ENV DOCKERIZE_VERSION v0.7.0

RUN apk update --no-cache \
  && apk add --no-cache wget openssl \
  && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
  && apk del wget

EXPOSE 3000

CMD ["dockerize", "-wait", "tcp://database:3306", "-timeout", "20s", "npm", "run", "dev" ]