version: '3'

services:
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile.nginx
    image: nginx:latest
    container_name: nginx
    tty: true
    restart: always
    ports:
      - "8080:80"
    networks:
      - netproject
    depends_on:
      - nodejs

  nodejs:
    build: 
      context: ./
      dockerfile: Dockerfile.nodejs
    image: nodejs:latest
    container_name: nodejs
    volumes:
      - /files
    tty: true
    restart: always
    working_dir: /usr/src/app
    command: npm run dev
    networks:
      - netproject
    depends_on:
      - database

  database:
    image: mysql:8.2.0
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=devproject
    networks:
      - netproject

networks:
  netproject:
    driver: bridge
